# Generated by Django 4.1.3 on 2022-12-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutecut_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
